### PR TITLE
Add _Scheduler_TimeToStamp

### PR DESCRIPTION
**Pull request by huynhphungdt**
I have rewritten the _Scheduler_TimeToStamp function according to your suggestion. Please take a look and help me. Thank you very much.

### CODE REVIEW

**Comment by TheDcoder** [comment]
Thanks, the code looks good to me. However before I merge this, can you update the commit message to be meaningful? Following my current convention, this would be a good commit message: `Add _Scheduler_TimeToStamp`

**Comment by huynhphungdt** [comment]
> Thanks, the code looks good to me. However before I merge this, can you update the commit message to be meaningful? Following my current convention, this would be a good commit message: `Add _Scheduler_TimeToStamp`

I have updated the commit message again. Thank you very much.

**Comment by TheDcoder** [comment]
Actually you just updated this PR's title, not the commit message. You can use the `git commit --amend` command to update the message :smile:

Make sure you force push because the history would've diverged as the older commit will be replaced with the new amended commit.

**Comment by huynhphungdt** [comment]
> Actually you just updated this PR's title, not the commit message. You can use the `git commit --amend` command to update the message 😄
> 
> Make sure you force push because the history would've diverged as the older commit will be replaced with the new amended commit.

@TheDcoder Thank you very much. I think I will have to seriously study a lot more things.

Please check your commit message for me.
Have a good day.

**Comment by TheDcoder** [comment]
@huynhphungdt Looks good to me, merged!

Good to see your interest in learning more. If you want to learn git I highly recommend reading the free "[Pro Git](https://git-scm.com/book/en/v2)" book :slightly_smiling_face:

**Pull request merged**
